### ISSUE TITLE
Determine Data Shapes - single ShoppingList

### ISSUE THREAD

**Issue by adumortier** [track-basket/trackbasket_BE#16]
## Issue
- [ ] Style (non-breaking style code)
- [ ] Testing (add testing to code)
- [ ] Bug fix (change which fixes an issue)
- [ ] Refactor (improvement to the code)
- [ ] New feature (change which adds functionality)
- [x] Chore
## Issue Summary
- determine the shape of data returned for a single shopping list (status, quantity, items, ...)
- this response comes back when the front end wants to see the shopping_list associated with a specific at risk person

## Resources 
List any resources used when working on the issue (e.g. links to articles, stackoverflow, etc.)

**Comment by adumortier** [comment]
`{
  "data": {
      "id": "shoppinglist",
      "attributes":
        {
          "status": "pending",
          "items": [
            {
              name: "Whole Wheat Bread",
              quantity: 2,
            }, 
            {
              name: "Tropicana Orange Juice",
              quantity: 1,
            }, 
            ...
          ], 
        }
}`

**Comment by monstaro** [comment]
We will need a few extra properties...
(we will send all these things to you in the shopping list)
`image` 
`productId` 
`aisleNumber`
`upc`
`storeId`
`latLng` (of the store)

**Comment by adumortier** [comment]
ok I'll make the changes, let me know if you'd prefer a different shape too, happy to make it more to your liking

**Comment by mronauli** [comment]
``` /api/v1/shoppinglists/:id ```

**Comment by edlsto** [comment]
We also need date/time submitted
