### ISSUE TITLE
Determine Data Shape - person at risk profile info

### ISSUE THREAD

**Issue by adumortier** [track-basket/trackbasket_BE#26]
## Issue
- [ ] Style (non-breaking style code)
- [ ] Testing (add testing to code)
- [ ] Bug fix (change which fixes an issue)
- [ ] Refactor (improvement to the code)
- [ ] New feature (change which adds functionality)
- [x] Chore
## Issue Summary

determine the information returned when the front end request the user profile information
 
## Resources 
List any resources used when working on the issue (e.g. links to articles, stackoverflow, etc.)

**Comment by adumortier** [comment]
```
{
      "data": 
            {
            "id": "user",
            "attributes": 
                  {
                   "id": "2334534",
                   "name": "John Doe", 
                   "address": "729 E 10th Avenue",
                   "city": "Denver",
                   "state": "Colorado",
                   "phone number": "(721) 400-1342",
                  }
            }
}
```

**Comment by monstaro** [comment]
This looks good to me, if @edlsto likes this too we can move this card to approved.

**Comment by mronauli** [comment]
``` /trackbasket/api/v1/profile/user ```
