### ISSUE TITLE
Determine Data Shape - volunteer profile info

### ISSUE THREAD

**Issue by adumortier** [track-basket/trackbasket_BE#27]
## Issue
- [ ] Style (non-breaking style code)
- [ ] Testing (add testing to code)
- [ ] Bug fix (change which fixes an issue)
- [ ] Refactor (improvement to the code)
- [ ] New feature (change which adds functionality)
- [x] Chore
## Issue Summary

prepare the data received by the front end when it requests a volunteer's profile

## Resources 
List any resources used when working on the issue (e.g. links to articles, stackoverflow, etc.)

**Comment by adumortier** [comment]
```
{
      "data": 
            {
            "id": "volunteer",
            "attributes": 
                  {
                   "id": "2334534",
                   "name": "Bob Doe", 
                   "phone number": (720) 300-4563            
                   "lat": 39.34534,
                   "lng": 123.3456,
                  }
            }
}
```

**Comment by mronauli** [comment]
``` /api/v1/volunteer/:id```
